version: '3'

services:
  db:
    image: mariadb:10
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=lei123
      - MYSQL_DATABASE=lei
      - CONNECT_TIMEOUT=60
    ports: 
      - 3306:3306
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
  redis:
    image: redis:latest
    restart: always
    ports: 
      - 6379:6379